version: "3.9"

services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - microservices-net

  api-gateway:
    container_name: api-gateway
    build: ./services/api-gateway
    ports:
      - "3003:3003"
    depends_on:
      - rabbitmq
    restart: always
    networks:
      - microservices-net

  order-service:
    container_name: order-service
    build: ./services/order-service
    ports:
      - "3001:3001"
    depends_on:
      - rabbitmq
    restart: always
    networks:
      - microservices-net

  payment-service:
    container_name: payment-service
    build: ./services/payment-service
    depends_on:
      - rabbitmq
    restart: always
    networks:
      - microservices-net

  notification-service:
    container_name: notification-service
    build: ./services/notification-service
    ports:
      - "3002:3002"
    depends_on:
      - rabbitmq
    restart: always
    networks:
      - microservices-net

  log-service:
    container_name: log-service
    build: ./services/log-service
    ports:
      - "3004:3004"
    depends_on:
      - rabbitmq
    restart: always
    networks:
      - microservices-net

  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - "9000:9000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - api-gateway
      - notification-service
    networks:
      - microservices-net

networks:
  microservices-net:
    driver: bridge
